catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - chokidar@4.0.3

packages:
  - packages/**
  - '!packages/create/template-js'
  - '!packages/create/template-ts'

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@docsearch/css': ^4.5.4
  '@docsearch/js': ^4.5.4
  '@floating-ui/dom': ^1.7.5
  '@iconify-json/bi': ^1.2.7
  '@iconify-json/bxs': ^1.2.2
  '@iconify-json/carbon': ^1.2.18
  '@iconify-json/emojione': ^1.2.3
  '@iconify-json/fxemoji': ^1.2.2
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/material-symbols': ^1.2.55
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/noto': ^1.2.7
  '@iconify-json/openmoji': ^1.2.21
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/solar': ^1.2.5
  '@iconify-json/tabler': ^1.2.26
  '@iconify-json/vscode-icons': ^1.2.42
  '@shikijs/twoslash': ^3.22.0
  '@sveltejs/adapter-static': ^3.0.10
  '@sveltejs/enhanced-img': ^0.9.3
  '@sveltejs/kit': ^2.52.0
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@types/cross-spawn': ^6.0.6
  '@types/estree': ^1.0.8
  '@types/fs-extra': ^11.0.4
  '@types/hast': ^3.0.4
  '@types/mdast': ^4.0.4
  '@types/minimist': ^1.2.5
  '@types/node': ^24.10.13
  '@types/prompts': ^2.4.9
  '@unocss/extractor-svelte': ^66.6.0
  '@vite-pwa/sveltekit': ^1.1.0
  changelogithub: ^14.0.0
  cross-spawn: ^7.0.6
  dayjs: ^1.11.19
  eslint: ^9.39.2
  eslint-plugin-svelte: ^3.15.0
  fs-extra: ^11.3.3
  husky: ^9.1.7
  lint-staged: ^16.2.7
  lru-cache: ^11.2.6
  mdast-util-from-markdown: ^2.0.2
  mdast-util-gfm: ^3.1.0
  mdast-util-to-hast: ^13.2.1
  minimist: ^1.2.8
  picocolors: ^1.1.1
  prettier: ~3.6.2
  prettier-plugin-svelte: ^3.4.1
  prompts: ^2.4.2
  rehype-stringify: ^10.0.1
  remark-directive: ^4.0.0
  remark-emoji: ^5.0.2
  remark-extract-frontmatter: ^3.2.0
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  remark-stringify: ^11.0.0
  shiki: ^3.22.0
  source-map-js: ^1.2.1
  svelte: ^5.51.2
  svelte-check: ^4.4.0
  svelte2tsx: ^0.7.48
  taze: ^19.9.2
  twoslash: ^0.3.6
  twoslash-protocol: ^0.3.6
  typescript: ^5.9.3
  uid: ^2.0.2
  unbuild: ^3.6.1
  unified: ^11.0.5
  unist-util-visit: ^5.1.0
  unocss: ^66.6.0
  vfile: ^6.0.3
  vite: ^7.3.1
  vite-plugin-inspect: ^11.3.3
  vitest: 4.0.14
  workbox-precaching: ^7.4.0
  workbox-routing: ^7.4.0
  workbox-window: ^7.4.0
  yaml: ^2.8.2
  zx: ^8.8.5
