packages:
  - 'packages/**'
  - '!packages/create/template-js'
  - '!packages/create/template-ts'

catalog:
  '@iconify-json/bi': ^1.2.6
  '@iconify-json/bxs': ^1.2.2
  '@iconify-json/carbon': ^1.2.14
  '@iconify-json/emojione': ^1.2.3
  '@iconify-json/fxemoji': ^1.2.2
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/material-symbols': ^1.2.48
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/noto': ^1.2.7
  '@iconify-json/openmoji': ^1.2.17
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/solar': ^1.2.5
  '@iconify-json/tabler': ^1.2.23
  '@iconify-json/vscode-icons': ^1.2.36
  '@shikijs/twoslash': ^1.29.2
  '@sveltejs/adapter-static': ^3.0.10
  '@sveltejs/kit': ^2.49.0
  '@sveltejs/package': ^2.5.6
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@types/node': ^22.19.1
  '@unocss/extractor-svelte': ^66.5.9
  eslint: ^9.39.1
  lru-cache: ^10.4.3
  mdast-util-from-markdown: ^2.0.2
  mdast-util-gfm: ^3.1.0
  shiki: ^3.15.0
  svelte: ^5.43.14
  typescript: ^5.9.3
  unocss: ^66.5.9
  vite: ^7.2.4
  vite-plugin-pwa: ^1.1.0
  vitest: ^4.0.13
  yaml: ^2.8.1
